### ISSUE TITLE
field_config table not found

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/taxonomy_menu#1]
When I try to create or edit a node of any type, I get this error:
```
EntityStorageException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydatabase.field_config' doesn't exist in NodeStorageController->save() (line 304 of /backdrop/core/modules/node/node.entity.inc).
```

Here's the section of code that refers to:
```
catch (Exception $e) {
      $transaction->rollback();
      watchdog_exception($this->entityType, $e);
      throw new EntityStorageException($e->getMessage(), (int) $e->getCode(), $e);
    }
```

In taxonomy_menu.database.inc we still have this query, which needs to be replaced with a config check:
```php
$result = db_query("SELECT field_name FROM {field_config} WHERE type = 'taxonomy_term_reference'");
  foreach ($result as $field) {
```

**Comment by klonos** [comment]
@jenlampton the module pretty much makes any website useless after installation without this fix. Can you please tag a new release? Thanx.

**Comment by jenlampton** [comment]
yes, it was my plan to do so later today!

**Comment by klonos** [comment]
...also https://github.com/backdrop-contrib/taxonomy_menu/pull/3 please? ...didn't file an issue for it cause I'm busy on a spree to rename all projects and file PRs for proper capitalization in .info files *cough* OCD *cough* 😄

**Comment by jenlampton** [comment]
But, the module name for this project is `Taxonomy menu` with a lower case m. See
https://www.drupal.org/project/taxonomy_menu

**Comment by jenlampton** [comment]
https://github.com/backdrop-contrib/taxonomy_menu/releases/tag/1.x-1.5.1
