### ISSUE TITLE
Hierarchy lost when regenerating terms for a vocab

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/taxonomy_menu#8]
Hierarchy lost when regenerating terms for a vocab

To reproduce:

1. Start with a clean installation of Backdrop
2. **PATCH** taxonomy menu with this pr: https://github.com/backdrop-contrib/taxonomy_menu/pull/12
3. Enable taxonomy_menu
4. Do not (yet) enable taxonomy menu for any of the site's vocabularies
5. Add a bunch of terms to the Tags vocabulary in the term UI. Do not assign terms to nodes. Be sure that there is some hierarchy of terms
6. Now, head to the configuration page for the Tags vocabulary
7. Enable taxonomy menu for the main menu
8. Be sure that "Add all menu items to the same level rather than retaining term hierarchy." is unchecked
9. Check "Rebuild the menu on submit"
10. Submit

All terms are added at the root level of the main menu, regardless of their hierarchy.

The problem is that, when ported, the module is missing some crucial lines. Specifically, `_taxonomy_menu_save()` never calls `_taxonomy_menu_insert_menu_item()`, which results in the `taxonomy_menu` table not being populated upon rebuilding of the menu links.  In fact, in the Backdrop version, `_taxonomy_menu_insert_menu_item()` is NEVER called, meaning that the table is never used.

**Comment by eric2pin** [comment]
This issue appears to be related to the _taxonomy_menu_save() function no longer calling _taxonomy_menu_insert_menu_item() which saves the menu / term mapping to the taxonomy_menu table. Adding that call back in fixes the issue (recreates the term hierarchy in the menu items) but I'm uncertain if there was some plan / decision to remove the menu/term mapping from the database.

I'll submit a pull request shortly if I can't find a reason these database inserts were removed.

**Comment by argiepiano** [comment]
Please see #13 (duplicate of this - sorry)  and PR #14.

**Comment by jenlampton** [comment]
I usually like to close the newer issues in favor of the older ones, so I've copied the STR from the newer issue here, since those were better. 

Also from the other comments:
> The PR #14 also fixes #11. So, to test, if you applied PR #12 you must revert it before applying #14.

**Comment by jenlampton** [comment]
https://github.com/backdrop-contrib/taxonomy_menu/pull/14 is merged.
